apiVersion: v1
kind: Secret
metadata:
  name: rustfs-credentials
  namespace: asphalt
type: Opaque
stringData:
  access-key: admin
  secret-key: adminsecret

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rustfs-settings
  namespace: asphalt
data:
  RUSTFS_VOLUMES: "/data/rustfs0"
  RUSTFS_ADDRESS: "0.0.0.0:9000"
  RUSTFS_CONSOLE_ADDRESS: "0.0.0.0:9001"
  RUSTFS_CONSOLE_ENABLE: "true"
  RUSTFS_CORS_ALLOWED_ORIGINS: "*"
  RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS: "*"
  RUSTFS_OBS_LOGGER_LEVEL: "info"
  RUSTFS_TLS_PATH: "/opt/tls"
  RUSTFS_OBJECT_CACHE_ENABLE: "true"
  RUSTFS_OBJECT_CACHE_TTL_SECS: "300"