# pvcs.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustfs-data-0
  namespace: asphalt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # adjust to your needs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustfs-logs
  namespace: asphalt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi