apiVersion: v1
kind: Namespace
metadata:
  name: asphalt

--- 
apiVersion: v1
kind: Namespace
metadata:
  name: flink

--- 
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

--- 
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
