# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: default-pvc
#   namespace: asphalt
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi