apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/default-2_2
patches: 
  - target:
      kind: FlinkDeployment
      name: flink-app
    path: flink-deployment.yaml
    options:
      allowNameChange: true