apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: asphalt
spec:
  type: ClusterIP
  selector:
    app: kafka
  ports:
    - name: broker
      targetPort: 29092
      port: 29092
    - name: controller
      targetPort: 29093
      port: 29093

---
# Used to debug from host machine 
apiVersion: v1
kind: Service
metadata:
  name: kafka-external
  namespace: asphalt
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
    - name: client
      targetPort: 9092
      port: 9092