name: Publish asphalt-core lib

on:
  workflow_dispatch:
    
jobs:
  publish_package:
    uses: ./.github/workflows/_publish_package.yaml
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      project_dir: 'libs/asphalt-core'
      deploy_command: 'mvn --batch-mode deploy'